### ISSUE TITLE
How to set env variables?

### ISSUE THREAD

**Issue by tarunparmar** [shafiquejamal/ishares-etf-data-download#1]
Hi @shafiquejamal , I was trying to reproduced this but wasnt sure how to set the env variables before starting. I did not see any `conf` folder so wanted to make sure I am not doing something on my own.

**Comment by shafiquejamal** [comment]
Sorry, that's a typo. I'll fix it. The environment variables are located in:

`src/main/resources/application.conf`

Make sure you set those environment variables in your shell before running any code in this repo. Please let me know how it goes.

**Comment by tarunparmar** [comment]
Thanks for quick response. 

Do I add stuff outside of the code that is there in `db{}` ?

And how do i define them? something like this ?

```
export ISHARES_DATA_DIR=/path/to/downloaded_files
export SECURITIESDATA_PROJECT_ROOT=/downloaded_project_root/
```

**Comment by shafiquejamal** [comment]
Yes, your exports look ok. You also have to set the database info:

export SECURITIESDATA_DEFAULT_DB_USERNAME=foo
export SECURITIESDATA_TEST_DB_USERNAME=foo
export SECURITIESDATA_DEFAULT_DB_PASSWORD=bar
export SECURITIESDATA_TEST_DB_PASSWORD=bar

(yes you have to set the environment variables for TEST as well). If you set all of the above environment variables (including ISHARES_DATA_DIR and SECURITIESDATA_PROJECT_ROOT), you should be good to go.

**Comment by shafiquejamal** [comment]
Sorry, you'll also need to set:

`SECURITIESDATA_DEFAULT_DB_DRIVER`

I used something like:

`export SECURITIESDATA_DEFAULT_DB_DRIVER=jdbc:postgresql://localhost:5432/securitiesdata`

and you'll need to create a test database called `securitiesdatatest`.

Please excuse the confusion - it has been a long time since I worked on this, and I now see how I could have improved the documentation.

**Comment by tarunparmar** [comment]
hehe :smile: no worries.

I saw some more errors when I added those variables earlier. 

```
[error] (*:flywayMigrate) org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:postgresql://localhost:5432/securitiesdata) for user '': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

**Comment by shafiquejamal** [comment]
Did you install postgres, start it on port 5432, and create the two databases (one of which should be `securitiesdatatest`)? 

Looks like the username and password for the postgres database user has not been set....

**Comment by shafiquejamal** [comment]
closing, as I have not heard anything more on this issue.
